# Generated by Django 3.1.1 on 2020-11-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Infected', 'Infected'), ('Deceased', 'Deceased'), ('Off-Isolated', 'Off-Isolated')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='RegionLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('no_infected', models.IntegerField()),
                ('no_deceased', models.IntegerField()),
                ('no_offisolated', models.IntegerField()),
                ('updated_time', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('no_infected', models.IntegerField()),
                ('no_deceased', models.IntegerField()),
                ('no_offisolated', models.IntegerField()),
                ('updated_time', models.DateTimeField()),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionlarge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('no_infected', models.IntegerField()),
                ('no_deceased', models.IntegerField()),
                ('no_offisolated', models.IntegerField()),
                ('updated_time', models.DateTimeField()),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionmedium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('sub_type', models.CharField(choices=[('Email', 'Email'), ('Kakao', 'Kakao')], max_length=5)),
                ('large_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionlarge')),
                ('medium_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionmedium')),
                ('small_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionsmall')),
            ],
        ),
        migrations.CreateModel(
            name='InfectedMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_date', models.DateTimeField()),
                ('exact_address', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=20)),
                ('infected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.infected')),
                ('small_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionsmall')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('fac_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Convenience', 'Convenience')], max_length=12)),
                ('small_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionsmall')),
            ],
        ),
    ]
