# Generated by Django 3.1.1 on 2020-11-29 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionsmall',
            name='parent_region',
        ),
        migrations.RemoveField(
            model_name='infectedmovement',
            name='small_region',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='small_region',
        ),
        migrations.AddField(
            model_name='infectedmovement',
            name='medium_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.regionmedium'),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='RegionSmall',
        ),
    ]
