# Generated by Django 3.1.1 on 2020-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20201129_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionlarge',
            name='prev_no_deceased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionlarge',
            name='prev_no_infected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionlarge',
            name='prev_no_offisolated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionmedium',
            name='prev_no_deceased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionmedium',
            name='prev_no_infected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionmedium',
            name='prev_no_offisolated',
            field=models.IntegerField(default=0),
        ),
    ]
