# Generated by Django 3.1.1 on 2020-12-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201201_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
